#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'

development:
  adapter: mysql2
  encoding: utf8
  database: agileDex_development_db
  pool: 5
  username: nilesh
  password: p20o20e13
  host: 192.168.2.19
  port: 3306
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: agileDex_test_db
  pool: 5
  username: nilesh
  password: p20o20e13
  host: 192.168.2.19
  port: 3306
  socket: /var/run/mysqld/mysqld.sock


production:
  adapter: mysql2
  encoding: utf8
  database: agileDex_production_db
  pool: 5
  username: nilesh
  password: p20o20e13
  host: 192.168.2.19
  port: 3306
  socket: /var/run/mysqld/mysqld.sock