#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'


development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  encoding: utf8
  database: agileDex_test_db
  pool: 5
  username: ptotem
  password: p20o20e13


production:
  adapter: postgresql
  encoding: utf8
  database: agileDex_production_db
  pool: 5
  username: ptotem
  password: p20o20e13

