#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'

development:
  adapter: postgresql
  encoding: utf8
  database: agileDex_development_db
  pool: 5
  username: nilesh
  password: p20o20e13
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: agileDex_test_db
  pool: 5
  username: nilesh
  password: p20o20e13
  host: localhost


production:
  adapter: postgresql
  encoding: utf8
  database: agileDex_production_db
  pool: 5
  username: nilesh
  password: p20o20e13