#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'


development:
  adapter: postgresql
  encoding: utf8
  database: agileDex_development_db
  pool: 5
  username: ptotem
  password: p20o20e13


test:
  adapter: postgresql
  encoding: utf8
  database: agileDex_test_db
  pool: 5
  username: ptotem
  password: p20o20e13


production:
  adapter: postgresql
  encoding: utf8
  database: agileDex_production_db
  pool: 5
  username: ptotem
  password: p20o20e13

